In [1]:
import warnings
import numpy as np
import pandas as pd
import xarray as xr
import fsspec

warnings.simplefilter('ignore') # filter some warning messages
xr.set_options(display_style="html")  #display dataset nicely

In [2]:
file_opendap = 'https://podaac-opendap.jpl.nasa.gov/opendap/allData/ghrsst/data/GDS2/L4/GLOB/JPL/MUR/v4.1/2015/001/20150101090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'
file_local = './../../data/20150101090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'
file_aws = 'https://mur-sst.s3.us-west-2.amazonaws.com/zarr-v1'
file_aws2 = 'https://mur-sst.s3.us-west-2.amazonaws.com/zarr'

In [3]:
%%time

ds_aws = xr.open_zarr(file_aws,consolidated=True)
ds_aws = ds_aws.sel(time='2015-01-01')
ds_aws

CPU times: user 1.62 s, sys: 157 ms, total: 1.78 s
Wall time: 2.11 s


<xarray.Dataset>
Dimensions:           (lat: 17999, lon: 36000, time: 1)
Coordinates:
  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99
  * lon               (lon) float32 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0
  * time              (time) datetime64[ns] 2015-01-01T09:00:00
Data variables:
    analysed_sst      (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
    analysis_error    (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
    mask              (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
    sea_ice_fraction  (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
Attributes:
    Conventions:                CF-1.7
    Metadata_Conventions:       Unidata Observation Dataset v1.0
    acknowledgment:             Please acknowledge the use of these data with...
    cdm_data_type:              grid
    comment:                    MUR = "Multi-scale Ultra-high Resolution"
    creator_email:              ghrsst@podaac.jpl.nasa.gov
    creator_name:               JPL MUR SST project
    creator_url:                http://mur.jpl.nasa.gov
    date_created:               20200124T010755Z
    easternmost_longitude:      180.0
    file_quality_level:         3
    gds_version_id:             2.0
    geospatial_lat_resolution:  0.009999999776482582
    geospatial_lat_units:       degrees north
    geospatial_lon_resolution:  0.009999999776482582
    geospatial_lon_units:       degrees east
    history:                    created at nominal 4-day latency; replaced nr...
    id:                         MUR-JPL-L4-GLOB-v04.1
    institution:                Jet Propulsion Laboratory
    keywords:                   Oceans > Ocean Temperature > Sea Surface Temp...
    keywords_vocabulary:        NASA Global Change Master Directory (GCMD) Sc...
    license:                    These data are available free of charge under...
    metadata_link:              http://podaac.jpl.nasa.gov/ws/metadata/datase...
    naming_authority:           org.ghrsst
    netcdf_version_id:          4.1
    northernmost_latitude:      90.0
    platform:                   Terra, Aqua, GCOM-W, MetOp-A, MetOp-B, Buoys/...
    processing_level:           L4
    product_version:            04.1
    project:                    NASA Making Earth Science Data Records for Us...
    publisher_email:            ghrsst-po@nceo.ac.uk
    publisher_name:             GHRSST Project Office
    publisher_url:              http://www.ghrsst.org
    references:                 http://podaac.jpl.nasa.gov/Multi-scale_Ultra-...
    sensor:                     MODIS, AMSR2, AVHRR, in-situ
    source:                     MODIS_T-JPL, MODIS_A-JPL, AMSR2-REMSS, AVHRRM...
    southernmost_latitude:      -90.0
    spatial_resolution:         0.01 degrees
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    start_time:                 20200116T090000Z
    stop_time:                  20200116T090000Z
    summary:                    A merged, multi-sensor L4 Foundation SST anal...
    time_coverage_end:          20200116T210000Z
    time_coverage_start:        20200115T210000Z
    title:                      Daily MUR SST, Final product
    uuid:                       27665bc0-d5fc-11e1-9b23-0800200c9a66
    westernmost_longitude:      -180.0

In [4]:
%%time

ds_aws2 = xr.open_zarr(file_aws2,consolidated=True)
ds_aws2 = ds_aws.sel(time='2015-01-01')
ds_aws2

CPU times: user 763 ms, sys: 47 ms, total: 810 ms
Wall time: 954 ms


<xarray.Dataset>
Dimensions:           (lat: 17999, lon: 36000, time: 1)
Coordinates:
  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99
  * lon               (lon) float32 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0
  * time              (time) datetime64[ns] 2015-01-01T09:00:00
Data variables:
    analysed_sst      (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
    analysis_error    (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
    mask              (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
    sea_ice_fraction  (time, lat, lon) float32 dask.array<chunksize=(1, 1799, 3600), meta=np.ndarray>
Attributes:
    Conventions:                CF-1.7
    Metadata_Conventions:       Unidata Observation Dataset v1.0
    acknowledgment:             Please acknowledge the use of these data with...
    cdm_data_type:              grid
    comment:                    MUR = "Multi-scale Ultra-high Resolution"
    creator_email:              ghrsst@podaac.jpl.nasa.gov
    creator_name:               JPL MUR SST project
    creator_url:                http://mur.jpl.nasa.gov
    date_created:               20200124T010755Z
    easternmost_longitude:      180.0
    file_quality_level:         3
    gds_version_id:             2.0
    geospatial_lat_resolution:  0.009999999776482582
    geospatial_lat_units:       degrees north
    geospatial_lon_resolution:  0.009999999776482582
    geospatial_lon_units:       degrees east
    history:                    created at nominal 4-day latency; replaced nr...
    id:                         MUR-JPL-L4-GLOB-v04.1
    institution:                Jet Propulsion Laboratory
    keywords:                   Oceans > Ocean Temperature > Sea Surface Temp...
    keywords_vocabulary:        NASA Global Change Master Directory (GCMD) Sc...
    license:                    These data are available free of charge under...
    metadata_link:              http://podaac.jpl.nasa.gov/ws/metadata/datase...
    naming_authority:           org.ghrsst
    netcdf_version_id:          4.1
    northernmost_latitude:      90.0
    platform:                   Terra, Aqua, GCOM-W, MetOp-A, MetOp-B, Buoys/...
    processing_level:           L4
    product_version:            04.1
    project:                    NASA Making Earth Science Data Records for Us...
    publisher_email:            ghrsst-po@nceo.ac.uk
    publisher_name:             GHRSST Project Office
    publisher_url:              http://www.ghrsst.org
    references:                 http://podaac.jpl.nasa.gov/Multi-scale_Ultra-...
    sensor:                     MODIS, AMSR2, AVHRR, in-situ
    source:                     MODIS_T-JPL, MODIS_A-JPL, AMSR2-REMSS, AVHRRM...
    southernmost_latitude:      -90.0
    spatial_resolution:         0.01 degrees
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    start_time:                 20200116T090000Z
    stop_time:                  20200116T090000Z
    summary:                    A merged, multi-sensor L4 Foundation SST anal...
    time_coverage_end:          20200116T210000Z
    time_coverage_start:        20200115T210000Z
    title:                      Daily MUR SST, Final product
    uuid:                       27665bc0-d5fc-11e1-9b23-0800200c9a66
    westernmost_longitude:      -180.0

In [5]:
ds_odap = xr.open_dataset(file_opendap)
ds_odap

<xarray.Dataset>
Dimensions:           (lat: 17999, lon: 36000, time: 1)
Coordinates:
  * time              (time) datetime64[ns] 2015-01-01T09:00:00
  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99
  * lon               (lon) float32 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0
Data variables:
    analysed_sst      (time, lat, lon) float32 ...
    analysis_error    (time, lat, lon) float32 ...
    mask              (time, lat, lon) float32 ...
    sea_ice_fraction  (time, lat, lon) float32 ...
Attributes:
    Conventions:                CF-1.5
    title:                      Daily MUR SST, Final product
    summary:                    A merged, multi-sensor L4 Foundation SST anal...
    references:                 http://podaac.jpl.nasa.gov/Multi-scale_Ultra-...
    institution:                Jet Propulsion Laboratory
    history:                    created at nominal 4-day latency; replaced nr...
    comment:                    MUR = "Multi-scale Ultra-high Reolution"
    license:                    These data are available free of charge under...
    id:                         MUR-JPL-L4-GLOB-v04.1
    naming_authority:           org.ghrsst
    product_version:            04.1
    uuid:                       27665bc0-d5fc-11e1-9b23-0800200c9a66
    gds_version_id:             2.0
    netcdf_version_id:          4.1
    date_created:               20150409T142756Z
    start_time:                 20150101T090000Z
    stop_time:                  20150101T090000Z
    time_coverage_start:        20141231T210000Z
    time_coverage_end:          20150101T210000Z
    file_quality_level:         1
    source:                     AVHRR19_G-NAVO, AVHRR_METOP_A-EUMETSAT, MODIS...
    platform:                   Aqua, DMSP, NOAA-POES, Suomi-NPP, Terra
    sensor:                     AMSR-E, AVHRR, MODIS, SSM/I, VIIRS, in-situ
    Metadata_Conventions:       Unidata Observation Dataset v1.0
    metadata_link:              http://podaac.jpl.nasa.gov/ws/metadata/datase...
    keywords:                   Oceans > Ocean Temperature > Sea Surface Temp...
    keywords_vocabulary:        NASA Global Change Master Directory (GCMD) Sc...
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    southernmost_latitude:      -90.0
    northernmost_latitude:      90.0
    westernmost_longitude:      -180.0
    easternmost_longitude:      180.0
    spatial_resolution:         0.01 degrees
    geospatial_lat_units:       degrees north
    geospatial_lat_resolution:  0.01 degrees
    geospatial_lon_units:       degrees east
    geospatial_lon_resolution:  0.01 degrees
    acknowledgment:             Please acknowledge the use of these data with...
    creator_name:               JPL MUR SST project
    creator_email:              ghrsst@podaac.jpl.nasa.gov
    creator_url:                http://mur.jpl.nasa.gov
    project:                    NASA Making Earth Science Data Records for Us...
    publisher_name:             GHRSST Project Office
    publisher_url:              http://www.ghrsst.org
    publisher_email:            ghrsst-po@nceo.ac.uk
    processing_level:           L4
    cdm_data_type:              grid

In [6]:
ds_local = xr.open_dataset(file_local)
ds_local

<xarray.Dataset>
Dimensions:           (lat: 17999, lon: 36000, time: 1)
Coordinates:
  * time              (time) datetime64[ns] 2015-01-01T09:00:00
  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99
  * lon               (lon) float32 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0
Data variables:
    analysed_sst      (time, lat, lon) float32 ...
    analysis_error    (time, lat, lon) float32 ...
    mask              (time, lat, lon) float32 ...
    sea_ice_fraction  (time, lat, lon) float32 ...
Attributes:
    Conventions:                CF-1.5
    title:                      Daily MUR SST, Final product
    summary:                    A merged, multi-sensor L4 Foundation SST anal...
    references:                 http://podaac.jpl.nasa.gov/Multi-scale_Ultra-...
    institution:                Jet Propulsion Laboratory
    history:                    created at nominal 4-day latency; replaced nr...
    comment:                    MUR = "Multi-scale Ultra-high Reolution"
    license:                    These data are available free of charge under...
    id:                         MUR-JPL-L4-GLOB-v04.1
    naming_authority:           org.ghrsst
    product_version:            04.1
    uuid:                       27665bc0-d5fc-11e1-9b23-0800200c9a66
    gds_version_id:             2.0
    netcdf_version_id:          4.1
    date_created:               20150409T142756Z
    start_time:                 20150101T090000Z
    stop_time:                  20150101T090000Z
    time_coverage_start:        20141231T210000Z
    time_coverage_end:          20150101T210000Z
    file_quality_level:         1
    source:                     AVHRR19_G-NAVO, AVHRR_METOP_A-EUMETSAT, MODIS...
    platform:                   Aqua, DMSP, NOAA-POES, Suomi-NPP, Terra
    sensor:                     AMSR-E, AVHRR, MODIS, SSM/I, VIIRS, in-situ
    Metadata_Conventions:       Unidata Observation Dataset v1.0
    metadata_link:              http://podaac.jpl.nasa.gov/ws/metadata/datase...
    keywords:                   Oceans > Ocean Temperature > Sea Surface Temp...
    keywords_vocabulary:        NASA Global Change Master Directory (GCMD) Sc...
    standard_name_vocabulary:   NetCDF Climate and Forecast (CF) Metadata Con...
    southernmost_latitude:      -90.0
    northernmost_latitude:      90.0
    westernmost_longitude:      -180.0
    easternmost_longitude:      180.0
    spatial_resolution:         0.01 degrees
    geospatial_lat_units:       degrees north
    geospatial_lat_resolution:  0.01 degrees
    geospatial_lon_units:       degrees east
    geospatial_lon_resolution:  0.01 degrees
    acknowledgment:             Please acknowledge the use of these data with...
    creator_name:               JPL MUR SST project
    creator_email:              ghrsst@podaac.jpl.nasa.gov
    creator_url:                http://mur.jpl.nasa.gov
    project:                    NASA Making Earth Science Data Records for Us...
    publisher_name:             GHRSST Project Office
    publisher_url:              http://www.ghrsst.org
    publisher_email:            ghrsst-po@nceo.ac.uk
    processing_level:           L4
    cdm_data_type:              grid

In [7]:
#ds_local.analysed_sst.sel(lat=slice(20,30),lon=slice(-120,-100)).isel(time=0).plot()

In [8]:
# print out value near land
xlat = 24
xlon = -100
print(ds_local.analysed_sst.sel(lat=24,lon=-100).isel(time=0).data)
print(ds_odap.analysed_sst.sel(lat=24,lon=-100).isel(time=0).data)
print(ds_aws.analysed_sst.sel(lat=24,lon=-100).isel(time=0).compute().data)
print(ds_aws2.analysed_sst.sel(lat=24,lon=-100).isel(time=0).compute().data)

nan
nan
nan
nan


In [9]:
#ds_local.analysed_sst.sel(lat=slice(20,30),lon=slice(100,120)).isel(time=0).plot()

In [10]:
# print out value near land
xlat = 21
xlon = 101
print(ds_local.analysed_sst.sel(lat=24,lon=-100).isel(time=0).data)
print(ds_odap.analysed_sst.sel(lat=24,lon=-100).isel(time=0).data)
print(ds_aws.analysed_sst.sel(lat=24,lon=-100).isel(time=0).compute().data)
print(ds_aws2.analysed_sst.sel(lat=24,lon=-100).isel(time=0).compute().data)

nan
nan
nan
nan


## looking at xarray .sel

In [11]:
print(ds_local.lat[10043:10049].data)

[10.44 10.45 10.46 10.47 10.48 10.49]


The results above show that (as expected) the lat coordinate has .01 precision

In [12]:
print('these should all be len=3 since slice is inclusive of first/last points')
print(ds_local.lat.sel(lat=slice(10.46,10.48)).data)
print(ds_local.lat.sel(lat=slice(10.45,10.47)).data,'missing first&last points')
print(ds_local.lat.sel(lat=slice(10.43,10.45)).data)
print(ds_local.lat.sel(lat=slice(10.47,10.49)).data)
print(ds_local.lat.sel(lat=slice(11.45,11.47)).data,'missing first&last points')

these should all be len=3 since slice is inclusive of first/last points
[10.46 10.47 10.48]
[10.46] missing first&last points
[10.43 10.44 10.45]
[10.47 10.48 10.49]
[11.46] missing first&last points


In [13]:
print('these should all be len=5 since slice is inclusive of first/last points')
print(ds_local.lat.sel(lat=slice(11.46,11.50)).data)
print(ds_local.lat.sel(lat=slice(11.45,11.49)).data,'missing first point')
print(ds_local.lat.sel(lat=slice(11.43,11.47)).data,'missing last point')
print(ds_local.lat.sel(lat=slice(11.41,11.45)).data,'missing first point')

these should all be len=5 since slice is inclusive of first/last points
[11.46 11.47 11.48 11.49 11.5 ]
[11.46 11.47 11.48 11.49] missing first point
[11.43 11.44 11.45 11.46] missing last point
[11.42 11.43 11.44 11.45] missing first point
